export { schemaUrls, type SchemaName } from "./schemas.js";
export { assertBundleRelativePath, validateBundleRelativePath, type BundlePathValidationResult } from "./bundlePaths.js";
export {
  IR_DOCUMENTS,
  IR_SCHEMA_IDS,
  IR_VERSION,
  schemaBackedDocuments,
  type IrDocumentName,
  type SchemaBackedIrDocumentName,
} from "./documents.js";
export type {
  IConformanceAssetReport,
  IConformanceAudioCommandReport,
  IConformanceAudioReport,
  IConformanceCameraViewReport,
  IConformanceEntityReport,
  IConformanceEnvironmentReport,
  IConformanceEventReport,
  IConformanceLightBudgetReport,
  IConformanceMaterialReport,
  IConformanceReport,
  IConformanceResourceReport,
  IConformanceRuntimeConfigReport,
  IConformanceSceneLifecycleReport,
  IConformanceSceneLifecycleTraceEvent,
  IConformanceScreenshotExportReport,
  IConformanceSystemReport,
  IConformanceSystemQueryReport,
  IConformanceUiNodeReport,
  IConformanceUiReport,
} from "./conformanceReport.js";
export {
  BEVY_CATALOG_RESIDUAL_ROWS,
  diagnoseBevyCatalogResidualDeclarations,
  type BevyCatalogResidualArea,
  type BevyCatalogResidualStatus,
  type IBevyCatalogAssetExportDeclaration,
  type IBevyCatalogCallbackComponentDeclaration,
  type IBevyCatalogCustomUiMaterialDeclaration,
  type IBevyCatalogGltfExtensionDeclaration,
  type IBevyCatalogImeDeclaration,
  type IBevyCatalogResidualDeclarations,
  type IBevyCatalogResidualRow,
  type IBevyCatalogUiRoutingDeclaration,
  type IBevyCatalogWindowPolicyDeclaration,
} from "./bevyCatalogResiduals.js";
export {
  diagnoseUnsupportedRuntimeDeclarations,
  validateRuntimeDiagnosticReport,
  type IRuntimeDiagnostic,
  type IRuntimeDiagnosticReport,
  type IRuntimeDiagnosticsValidationResult,
  type RuntimeDiagnosticSeverity,
} from "./runtimeDiagnostics.js";
export {
  validateAssetReloadReport,
  type AssetReloadChangeKind,
  type AssetReloadClassification,
  type AssetReloadSchema,
  type AssetReloadStatePolicy,
  type IAssetReloadChangeIr,
  type IAssetReloadReportIr,
} from "./assetReload.js";
export {
  MAX_GLTF_EXTRAS_BYTES,
  MAX_GLTF_EXTRAS_DEPTH,
  validateGltfSceneMetadata,
  type IGltfCustomAttributeIr,
  type IGltfSceneAssetIr,
  type IGltfSceneMetadataIr,
  type IGltfSceneNodeIr,
  type IGltfNodeTransformIr,
} from "./gltfScene.js";
export {
  normalizeGltfSceneHandlesIr,
  validateGltfSceneHandlesIr,
  type GltfSceneHandlesSchema,
  type IGltfNodeHandleIr,
  type IGltfNodeOperationIr,
  type IGltfSceneHandlesIr,
} from "./gltfSceneHandles.js";
export {
  sortedPersistedBindingOverrides,
  type ControlsSettingsAxisSlot,
  type ControlsSettingsCaptureState,
  type ControlsSettingsTargetKind,
  type IControlsSettingsIr,
  type IControlsSettingsRowIr,
  type IInputActionIr,
  type IInputAxisIr,
  type IInputIr,
  type IPersistedBindingOverrideIr,
  type InputBinding,
} from "./input.js";
export {
  validatePickingIr,
  type IPickingDebugOverlayIr,
  type IPickingDragTargetIr,
  type IPickingIr,
  type PickingAxisConstraint,
  type PickingCancelPolicy,
  type PickingDragPhase,
  type PickingPointerEvents,
  type PickingTargetKind,
} from "./picking.js";
export type { IRuntimeConfigIr, RendererAntialiasMode } from "./runtimeConfig.js";
export { auditUiAccessibility, type IUiAccessibilityDiagnostic, type IUiAccessibilityReport } from "./uiAccessibility.js";
export {
  buildComponentReflectionRegistry,
  type IComponentReflectionField,
  type IComponentReflectionRegistry,
  type IComponentReflectionType,
} from "./reflection.js";
export type {
  IIrSystemDeclaration,
  IIrSystemQuery,
  IIrStateSource,
  IIrComponentHookDeclaration,
  IIrObserverDeclaration,
  IrComponentHookKind,
  IrSystemCommand,
  IrObserverPhase,
  IrSystemSchedule,
  IrSystemService,
  ISystemsIr,
} from "./systems.js";
export type {
  IAssetIr,
  IAssetsManifest,
  GltfSceneSchema,
  IAnimationsIr,
  IAtmosphereProfileIr,
  IAudioIr,
  IAudioBusIr,
  IAudioDuckingRuleIr,
  IAudioEmitterIr,
  IAudioListenerIr,
  IAudioMusicIr,
  IAudioMusicTransitionIr,
  IAudioOneShotIr,
  IAudioToneIr,
  IBundleManifest,
  ILocalDataAutosaveIr,
  ILocalDataIr,
  ILocalDataMigrationIr,
  ILocalDataSaveSlotIr,
  ILocalDataSchemaEntryIr,
  ILocalDataSettingIr,
  ISceneLifecycleIr,
  IScenesIr,
  ISceneTransitionIr,
  IActiveCameraResource,
  IActiveCamerasResource,
  ICameraClear,
  ICameraComponent,
  ICameraFollowHelper,
  ICameraOrbitHelper,
  ICameraOutputConfig,
  ICameraPanHelper,
  ICameraPortableProjection,
  ICameraBackendProjection,
  ICameraProjection,
  ICameraScreenShakeHelper,
  ICameraTarget,
  ICameraTargetBackbuffer,
  ICameraTargetDepth,
  ICameraTargetTexture,
  ICameraViewModelHelper,
  ICameraViewport,
  ICameraZoomHelper,
  IRenderLayersComponent,
  IColliderComponent,
  IEnvironmentInstanceIr,
  IEnvironmentCameraBookmarkIr,
  IEnvironmentExclusionZoneIr,
  IEnvironmentPathIr,
  IEnvironmentSceneIr,
  IEnvironmentScatterSpecIr,
  IEnvironmentSourceAssetIr,
  IEnvironmentTextureSourceIr,
  IEnvironmentTerrainIr,
  IFirstPersonControllerIr,
  IWalkabilityIr,
  IIrNamedSchema,
  IIrSchemaField,
  IIrSchemaFile,
  IrSchemaFieldKind,
  ILightComponent,
  IMaterialIr,
  IMaterialsIr,
  IMeshRendererComponent,
  IRigidBodyComponent,
  ITargetProfile,
  ITransformComponent,
  IUiBinding,
  IUiIr,
  IUiNodeIr,
  IWorldEntity,
  IWorldIr,
  Quat,
  SceneActivationPolicy,
  SceneLifecycleKind,
  ScenesSchema,
  SceneTransitionKind,
  SchemaVersion,
  Vec3,
} from "./types.js";
export { validateBundle, type IBundleValidationResult, type IIrDiagnostic } from "./validate.js";
export { validateCameraViews } from "./camera.js";
export { validateEnvironmentSceneIr } from "./environment.js";
export {
  validateOverlayEntry,
  validateOverlaysIr,
  type IOverlayBridgeMessages,
  type IOverlayIr,
  type IOverlayMessageDeclaration,
  type IOverlayMessageSchema,
  type IOverlaysIr,
  type OverlayInputMode,
  type OverlayMessageSchemaKind,
  type OverlayTargetProfile,
} from "./overlays.js";
export {
  buildEditorInspectorSnapshot,
  buildEditorToolSnapshot,
  buildEditorVisualPanelSnapshot,
  diffEditorProjectSnapshots,
  validateEditorPropertyEdit,
  validateEditorProjectSnapshot,
  type EditorProjectDiffOperation,
  type EditorVisualPanelKind,
  type IEditorEditableProperty,
  type IEditorHotReloadPolicy,
  type IEditorInspectorNode,
  type IEditorInspectorSnapshot,
  type IEditorProjectSnapshot,
  type IEditorAssetPreview,
  type IEditorGamepadViewerSnapshot,
  type IEditorSceneViewerSnapshot,
  type IEditorToolSnapshot,
  type IEditorVisualPanel,
  type IEditorVisualPanelRow,
  type IEditorVisualPanelSnapshot,
} from "./editorProject.js";
export {
  buildSceneInspectionReport,
  type ISceneInspectionDocuments,
  type ISceneInspectionReport,
  type SceneInspectionSchema,
} from "./sceneInspection.js";
export { validatePerformanceProfile, type PerformanceMetricName } from "./performanceProfile.js";
