export { SdkError } from "./errors.js";
export {
  defineAnimations,
  transformAnimationClip,
  type IAnimationsDeclaration,
  type ITransformAnimationClipDeclaration,
  type ITransformAnimationKeyframe,
  type ITransformAnimationTrack,
  type TransformAnimationChannel,
  type TransformAnimationEasing,
  type TransformAnimationLoop,
} from "./animation.js";
export {
  audioPlaybackControl,
  audioBus,
  audioDuckingRule,
  audioListener,
  defineAudio,
  generatedTone,
  loopingMusic,
  musicTransition,
  oneShotSound,
  spatialAudioEmitter,
  type AudioAttenuationCurveKind,
  type AudioListenerBindingKind,
  type AudioMusicTransitionKind,
  type AudioPlaybackControlKind,
  type AudioToneWaveform,
  type IAudioAttenuationDeclaration,
  type IAudioBusDeclaration,
  type IAudioDeclaration,
  type IAudioDuckingRuleDeclaration,
  type IAudioEmitterDeclaration,
  type IAudioListenerDeclaration,
  type IAudioListenerBindingDeclaration,
  type IAudioMusicDeclaration,
  type IAudioMusicTransitionDeclaration,
  type IAudioOneShotDeclaration,
  type IAudioPlaybackControlDeclaration,
  type IAudioToneDeclaration,
  type IScriptAudioPlayOptions,
  type IScriptAudioPlayResult,
  type IScriptAudioQueryResult,
  type IScriptAudioRuntimeState,
  type IScriptAudioStopResult,
  type ScriptAudioPlaybackKind,
  type ScriptAudioPlaybackStatus,
} from "./audio.js";
export {
  animationClip,
  animationEvent,
  animationGraph,
  assetGroup,
  audioAsset,
  boundedParticleEmitter,
  embeddedAsset,
  modelAsset,
  networkAsset,
  renderTargetAsset,
  textureAsset,
  type AssetCachePolicy,
  type AssetFormat,
  type AssetGroupFailurePolicy,
  type AssetKind,
  type AssetSourceMode,
  type IAnimationEventMarker,
  type IAnimationGraphDeclaration,
  type IAnimationGraphParameter,
  type IAnimationGraphState,
  type IAnimationGraphTransition,
  type IAnimationClipReference,
  type IAnimationMaskReference,
  type IAssetGroupDeclaration,
  type IAssetGroupOptions,
  type IAssetReference,
  type IBoundedParticleEmitter,
  type IEmbeddedAssetSource,
  type IMorphClipReference,
  type IMorphTargetReference,
  type INetworkAssetSource,
  type ITextureAssetOptions,
  type IUnsupportedAnimationAssetOptions,
  type TextureMagFilter,
  type TextureMinFilter,
  type TextureWrapMode,
} from "./assets.js";
export {
  CharacterController,
  characterController,
  type CharacterGroundingMode,
  type ICharacterControllerDeclaration,
  type ICharacterControllerOptions,
  type ICharacterPushPolicy,
  type IUnsupportedCharacterControllerOptions,
} from "./character.js";
export { defineControls, type IControlActionRecipe, type IControlsOptions, type IWasdMovementOptions } from "./controls.js";
export {
  World,
  type IWorldCommandDeclaration,
  type IWorldEntityDeclaration,
  type IWorldQueryDeclaration,
  type IWorldSnapshot,
  type IWorldSystemDeclaration,
} from "./ecs/World.js";
export { defineQuery, type IQueryDeclaration, type IQueryOptions } from "./ecs/query.js";
export * as commands from "./ecs/commands.js";
export type { CommandDeclaration, EntityRef } from "./ecs/commands.js";
export {
  defineSystem,
  fixedUpdate,
  postUpdate,
  startup,
  update,
  type ISystemContext,
  type ISystemDeclaration,
  type ISystemEntity,
  type ISystemOptions,
  type IV4SystemConfig,
  type PortableSystem,
  type SystemSchedule,
  type SystemService,
} from "./ecs/system.js";
export {
  defineComponent,
  defineEvent,
  defineResource,
  defineTag,
  type EcsFactory,
  type IEcsDeclaration,
  type IEcsSchema,
  type ISchemaField,
  type SchemaFieldDefinition,
  type SchemaFieldKind,
  type SchemaFields,
  type SchemaKind,
} from "./ecs/schema.js";
export {
  AnnulusGeometry,
  BoxGeometry,
  CapsuleGeometry,
  CircleGeometry,
  ConeGeometry,
  ConicalFrustumGeometry,
  CustomMeshGeometry,
  CylinderGeometry,
  ExtrudedRectangleGeometry,
  type ICustomMeshAttribute,
  type MeshAttributeItemSize,
  type MeshAttributeName,
  PlaneGeometry,
  RegularPolygonGeometry,
  SphereGeometry,
  TorusGeometry,
  type SupportedGeometry,
} from "./geometry/primitives.js";
export { MeshBuilder, type IMeshBuilderBuildOptions } from "./geometry/meshBuilder.js";
export { mushroom, pineTree, rock, stylizedTree, type IOrganicMeshOptions } from "./geometry/meshBuilderOrganic.js";
export { defineGame, type IGameRoot, type IGameRootOptions } from "./game.js";
export {
  defineScene,
  sceneTransition,
  type ISceneAudioDeclaration,
  type ISceneLifecycleDeclaration,
  type ISceneLifecycleOptions,
  type IScenePersistenceDeclaration,
  type IScenePreloadDeclaration,
  type ISceneTransitionDeclaration,
  type SceneActivationPolicy,
  type SceneLifecycleKind,
  type SceneTransitionKind,
} from "./sceneLifecycle.js";
export {
  gltfNodeHandle,
  gltfSceneHandles,
  lookupGltfNodeExtras,
  setGltfNodeMaterial,
  setGltfNodeTransform,
  setGltfNodeVisibility,
  type GltfNodeHandleOperation,
  type IGltfNodeHandleDeclaration,
  type IGltfNodeTransformOverride,
  type IGltfSceneHandlesDeclaration,
} from "./gltfScene.js";
export {
  environmentMap,
  lightProbe,
  skybox,
  EnvironmentMapDeclaration,
  LightProbeDeclaration,
  SkyboxDeclaration,
  type EnvironmentTextureIntent,
  type EnvironmentTextureMode,
  type EnvironmentTextureSourceDeclaration,
  type IEnvironmentCubemapFacesDeclaration,
  type IEnvironmentMapDeclarationJson,
  type IEnvironmentTextureSourceJson,
  type ILightProbeDeclarationJson,
  type ISkyboxDeclarationJson,
} from "./environment.js";
export {
  debugBounds,
  debugBox,
  debugCameraFrustum,
  debugLightVolume,
  debugLine,
  debugRay,
  debugSphere,
  debugTextLabel,
  debugTransformAxes,
  debugUiNodeRect,
  defineDebugDiagnostics,
  diagnosticCounter,
  fpsOverlay,
  platformAudioDiagnostic,
  unsupportedFeatureDiagnostic,
  unsupportedNetworkingDiagnostic,
  type DebugCounterAggregation,
  type DebugPrimitiveKind,
  type DebugSeverity,
  type IDebugCounterDeclaration,
  type IDebugDiagnosticsDeclaration,
  type IDebugDrawDeclaration,
  type IDebugFpsOverlayDeclaration,
  type IDebugPlatformDiagnosticDeclaration,
} from "./debug.js";
export {
  autosave,
  definePersistence,
  persistenceMigration,
  persistComponent,
  persistResource,
  persistSetting,
  saveSlot,
  type IAutosaveDeclaration,
  type IPersistedComponentDeclaration,
  type IPersistedResourceDeclaration,
  type IPersistenceDeclaration,
  type IPersistenceMigrationDeclaration,
  type IPersistenceSettingDeclaration,
  type ISaveSlotDeclaration,
  type PersistenceSettingGroup,
  type PersistenceSettingKind,
} from "./persistence.js";
export {
  action,
  axis,
  controlsSettings,
  defineInputMap,
  gamepad,
  keyboard,
  pointerAxis,
  pointerButton,
  touchControl,
  type IInputActionDeclaration,
  type IInputAxisDeclaration,
  type IControlsSettingsDeclaration,
  type IControlsSettingsRowDeclaration,
  type ControlsSettingsRowOptions,
  type IInputMapDeclaration,
  type IPersistedBindingOverrideDeclaration,
  type InputBinding,
} from "./input.js";
export { MeshExtendedMaterial, type ExtendedMaterialPreset, type IMeshExtendedMaterialOptions } from "./materials/MeshExtendedMaterial.js";
export { MeshStandardMaterial, type ColorValue, type IMaterialEmissiveBloomOptions, type MaterialAlphaMode, type MaterialBlendMode, type TextureSlotReference } from "./materials/MeshStandardMaterial.js";
export { Vector3, type Vector3Tuple } from "./math/Vector3.js";
export {
  staticNavigation,
  type INavigationPathQueryDeclaration,
  type INavigationRegionDeclaration,
  type IStaticNavigationDeclaration,
  type NavigationPoint2,
  type NavigationPoint3,
} from "./navigation.js";
export {
  overlay,
  type IOverlayDeclaration,
  type IOverlayMessageDeclaration,
  type IOverlayMessageSchema,
  type IOverlayMountOptions,
  type OverlayInputMode,
  type OverlayMessageSchemaKind,
  type OverlayTargetProfile,
} from "./overlay.js";
export {
  validateUiWidgetSupport,
  type IUnsupportedUiWidgetOptions,
} from "./ui.js";
export {
  boxCollider,
  capsuleCollider,
  cylinderCollider,
  meshCollider,
  physics,
  physicsJoint,
  rigidBody,
  sphereCollider,
  type IColliderSlopeDeclaration,
  type ICcdDeclaration,
  type IColliderDeclaration,
  type IMeshColliderDeclaration,
  type IPhysicsDeclaration,
  type IPhysicsJointDeclaration,
  type IPhysicsMaterialOptions,
  type IRigidBodyDeclaration,
  type ISensorDeclaration,
  type PhysicsBodyKind,
  type PhysicsColliderKind,
  type SensorPhase,
} from "./physics.js";
export {
  PrefabModelAsset,
  PrefabTransform,
  definePrefab,
  modelActorPrefab,
  primitiveActorPrefab,
  type IModelActorPrefabOptions,
  type IPrefabDeclaration,
  type IPrimitiveActorPrefabDeclaration,
  type IPrimitiveActorPrefabOptions,
} from "./prefab.js";
export { OrthographicCamera, PerspectiveCamera } from "./scene/Camera.js";
export { AmbientLight, DirectionalLight, PointLight, SpotLight } from "./scene/Light.js";
export { Group, type IGroupOptions } from "./scene/Group.js";
export { Mesh } from "./scene/Mesh.js";
export { Object3D } from "./scene/Object3D.js";
export { Scene } from "./scene/Scene.js";
export { defineRuntimeConfig, type IRuntimeConfigDeclaration } from "./time.js";
