export { SdkError } from "./errors.js";
export {
  defineAssetModule,
  defineAudioModule,
  defineEntity,
  defineInputModule,
  definePrefabModule,
  defineResourceModule,
  defineSceneModule,
  defineUiModule,
  defineWorldModule,
  type IAssetModuleDeclaration,
  type IAudioModuleDeclaration,
  type IEntityModuleDeclaration,
  type IEntityModuleOptions,
  type IInputModuleDeclaration,
  type IAuthoringSourceMetadata,
  type IPrefabModuleDeclaration,
  type IResourceModuleDeclaration,
  type ISceneModuleDeclaration,
  type ISceneModuleOptions,
  type IUiModuleDeclaration,
  type IWorldModuleOptions,
} from "./authoring.js";
export {
  defineAnimations,
  transformAnimationClip,
  type IAnimationsDeclaration,
  type IParticleCommandOptions,
  type IParticleCommandResult,
  type ITransformAnimationClipDeclaration,
  type ITransformAnimationKeyframe,
  type ITransformAnimationTrack,
  type ParticleCommandAliasName,
  type ParticleCommandName,
  type ParticleCommandServiceName,
  type TransformAnimationChannel,
  type TransformAnimationEasing,
  type TransformAnimationLoop,
} from "./animation.js";
export {
  audioPlaybackControl,
  audioBus,
  audioDuckingRule,
  audioListener,
  defineAudio,
  generatedTone,
  loopingMusic,
  musicTransition,
  oneShotSound,
  spatialAudioEmitter,
  type AudioAttenuationCurveKind,
  type AudioListenerBindingKind,
  type AudioMusicTransitionKind,
  type AudioPlaybackControlKind,
  type AudioToneWaveform,
  type IAudioAttenuationDeclaration,
  type IAudioBusDeclaration,
  type IAudioDeclaration,
  type IAudioDuckingRuleDeclaration,
  type IAudioEmitterDeclaration,
  type IAudioListenerDeclaration,
  type IAudioListenerBindingDeclaration,
  type IAudioMusicDeclaration,
  type IAudioMusicTransitionDeclaration,
  type IAudioOneShotDeclaration,
  type IAudioPlaybackControlDeclaration,
  type IAudioToneDeclaration,
  type IScriptAudioPlayOptions,
  type IScriptAudioPlayResult,
  type IScriptAudioQueryResult,
  type IScriptAudioRuntimeState,
  type IScriptAudioStopResult,
  type ScriptAudioPlaybackKind,
  type ScriptAudioPlaybackStatus,
} from "./audio.js";
export {
  ASSET_FORMATS_BY_KIND,
  animationClip,
  animationEvent,
  animationGraph,
  assetGroup,
  audioAsset,
  boundedParticleEmitter,
  embeddedAsset,
  modelAsset,
  networkAsset,
  renderTargetAsset,
  textureAsset,
  type AssetCachePolicy,
  type AssetFormat,
  type AssetGroupFailurePolicy,
  type AssetKind,
  type AssetSourceMode,
  type IAnimationEventMarker,
  type IAnimationGraphDeclaration,
  type IAnimationGraphParameter,
  type IAnimationGraphState,
  type IAnimationGraphTransition,
  type IAnimationClipReference,
  type IAnimationMaskReference,
  type IAssetGroupDeclaration,
  type IAssetGroupOptions,
  type IAssetReference,
  type IBoundedParticleEmitter,
  type IEmbeddedAssetSource,
  type IMorphClipReference,
  type IMorphTargetReference,
  type INetworkAssetSource,
  type ITextureAssetOptions,
  type IUnsupportedAnimationAssetOptions,
  type TextureMagFilter,
  type TextureMinFilter,
  type TextureWrapMode,
} from "./assets.js";
export {
  CharacterController,
  characterController,
  type CharacterGroundingMode,
  type ICharacterControllerDeclaration,
  type ICharacterControllerOptions,
  type ICharacterPushPolicy,
  type IUnsupportedCharacterControllerOptions,
} from "./character.js";
export { defineControls, type IControlActionRecipe, type IControlsOptions, type IWasdMovementOptions } from "./controls.js";
export {
  World,
  type IWorldCommandDeclaration,
  type IWorldEntityDeclaration,
  type IWorldQueryDeclaration,
  type IWorldSnapshot,
  type IWorldSystemDeclaration,
} from "./ecs/World.js";
export { defineQuery, type IQueryDeclaration, type IQueryOptions } from "./ecs/query.js";
export * as commands from "./ecs/commands.js";
export type { CommandDeclaration, EntityRef } from "./ecs/commands.js";
export {
  defineSystem,
  fixedUpdate,
  postUpdate,
  startup,
  update,
  type ISystemContext,
  type ISystemDelayedCommandDeclaration,
  type ISystemDelayedCommandOwnership,
  type ISystemDeclaration,
  type ISystemEntity,
  type ISystemOptions,
  type ISystemScriptSourceReference,
  type IV4SystemConfig,
  type IScheduleAfterTicksOptions,
  type IScheduleAfterTicksResult,
  type PortableSystem,
  type SystemDelayedCommandCancelPolicy,
  type SystemSchedule,
  type SystemService,
} from "./ecs/system.js";
export {
  defineComponent,
  defineEvent,
  defineResource,
  defineTag,
  type EcsFactory,
  type IEcsDeclaration,
  type IEcsSchema,
  type ISchemaField,
  type SchemaFieldDefinition,
  type SchemaFieldKind,
  type SchemaFields,
  type SchemaKind,
} from "./ecs/schema.js";
export {
  AnnulusGeometry,
  BoxGeometry,
  CapsuleGeometry,
  CircleGeometry,
  ConeGeometry,
  ConicalFrustumGeometry,
  CustomMeshGeometry,
  CylinderGeometry,
  ExtrudedRectangleGeometry,
  type ICustomMeshAttribute,
  type ICustomMeshColliderHint,
  type ICustomMeshLodLevel,
  type MeshAttributeItemSize,
  type MeshAttributeName,
  PlaneGeometry,
  RegularPolygonGeometry,
  SphereGeometry,
  TorusGeometry,
  type SupportedGeometry,
} from "./geometry/primitives.js";
export {
  MeshBuilder,
  type IMeshBuilderBoxOptions,
  type IMeshBuilderBuildOptions,
  type IMeshBuilderCapsuleOptions,
  type IMeshBuilderCoherentNoiseOptions,
  type IMeshBuilderConeOptions,
  type IMeshBuilderCylinderOptions,
  type IMeshBuilderExtrudeOptions,
  type IMeshBuilderLatheOptions,
  type IMeshBuilderLodLevelOptions,
  type IMeshBuilderMirrorOptions,
  type IMeshBuilderParametricOptions,
  type IMeshBuilderPlaneOptions,
  type IMeshBuilderPrimitiveOptions,
  type IMeshBuilderPrismOptions,
  type IMeshBuilderRawOptions,
  type IMeshBuilderRoundedBoxOptions,
  type IMeshBuilderSphereOptions,
  type IMeshBuilderSubdivideOptions,
  type IMeshBuilderTorusOptions,
  type IMeshBuilderTubeOptions,
  type IMeshBuilderWeldOptions,
} from "./geometry/meshBuilder.js";
export {
  arch,
  assertOrganicMeshHelperFixtureEnrollment,
  buildOrganicMeshHelper,
  bush,
  crate,
  crystal,
  fencePost,
  mushroom,
  organicMeshFixtureEnrollments,
  organicMeshHelperRegistry,
  organicMeshHelpers,
  pineTree,
  rock,
  stylizedTree,
  type IOrganicMeshFixtureEnrollment,
  type IOrganicMeshHelperDescriptor,
  type IOrganicMeshOptions,
  type OrganicMeshHelperName,
} from "./geometry/meshBuilderOrganic.js";
export { defineGame, type IGameRoot, type IGameRootOptions } from "./game.js";
export {
  defineTypedGameSpec,
  type IGameSpecIds,
  type ITypedEntityComponents,
  type ITypedEntitySpec,
  type ITypedGameSpec,
  type ITypedInputSpec,
  type ITypedMaterialSpec,
  type ITypedResourceSpec,
  type ITypedSceneSpec,
  type ITypedSystemSpec,
  type ITypedTransformSpec,
  type ITypedUiSpec,
} from "./gameSpecTypes.js";
export {
  RippleWater,
  StylizedNature,
  StylizedSparkles,
  rippleWater,
  stylizedNature,
  stylizedSparkles,
  type IRippleWaterComponent,
  type IRippleWaterOptions,
  type IStylizedNatureComponent,
  type IStylizedNatureOptions,
  type IStylizedSparklesComponent,
  type IStylizedSparklesOptions,
  type StylizedNatureDensity,
} from "./stylizedNature.js";
export {
  defineScene,
  sceneTransition,
  type ISceneAudioDeclaration,
  type ISceneLifecycleDeclaration,
  type ISceneLifecycleOptions,
  type IScenePersistenceDeclaration,
  type IScenePreloadDeclaration,
  type ISceneTransitionDeclaration,
  type SceneActivationPolicy,
  type SceneLifecycleKind,
  type SceneTransitionKind,
} from "./sceneLifecycle.js";
export {
  balancedRenderLook,
  cinematicRenderLook,
  parityRenderLook,
  renderLookProfile,
  stylizedRenderLook,
  type IRenderLookOverrides,
  type IRenderLookProfileDeclaration,
  type RenderLookProfileName,
  type RenderLookShadowQuality,
} from "./render-look.js";
export {
  scriptLifecycle,
  type IScriptLifecycleOptions,
} from "./scriptLifecycle.js";
export {
  gltfNodeHandle,
  gltfSceneHandles,
  lookupGltfNodeExtras,
  setGltfNodeMaterial,
  setGltfNodeTransform,
  setGltfNodeVisibility,
  type GltfNodeHandleOperation,
  type IGltfNodeHandleDeclaration,
  type IGltfNodeTransformOverride,
  type IGltfSceneHandlesDeclaration,
} from "./gltfScene.js";
export {
  environmentMap,
  lightProbe,
  skybox,
  EnvironmentMapDeclaration,
  LightProbeDeclaration,
  SkyboxDeclaration,
  type EnvironmentTextureIntent,
  type EnvironmentTextureMode,
  type EnvironmentTextureSourceDeclaration,
  type IEnvironmentCubemapFacesDeclaration,
  type IEnvironmentMapDeclarationJson,
  type IEnvironmentTextureSourceJson,
  type ILightProbeDeclarationJson,
  type ISkyboxDeclarationJson,
} from "./environment.js";
export {
  debugBounds,
  debugBox,
  debugCameraFrustum,
  debugLightVolume,
  debugLine,
  debugRay,
  debugSphere,
  debugTextLabel,
  debugTransformAxes,
  debugUiNodeRect,
  defineDebugDiagnostics,
  diagnosticCounter,
  fpsOverlay,
  platformAudioDiagnostic,
  unsupportedFeatureDiagnostic,
  unsupportedNetworkingDiagnostic,
  type DebugCounterAggregation,
  type DebugPrimitiveKind,
  type DebugSeverity,
  type IDebugCounterDeclaration,
  type IDebugDiagnosticsDeclaration,
  type IDebugDrawDeclaration,
  type IDebugFpsOverlayDeclaration,
  type IDebugPlatformDiagnosticDeclaration,
} from "./debug.js";
export {
  autosave,
  definePersistence,
  persistenceMigration,
  persistComponent,
  persistResource,
  persistSetting,
  saveSlot,
  type IAutosaveDeclaration,
  type IPersistedComponentDeclaration,
  type IPersistedResourceDeclaration,
  type IPersistenceDeclaration,
  type IPersistenceMigrationDeclaration,
  type IPersistenceMigrationOperationDeclaration,
  type IPersistenceMigrationTransformDeclaration,
  type IPersistenceSettingDeclaration,
  type ISaveSlotDeclaration,
  type PersistenceSettingGroup,
  type PersistenceSettingKind,
  type PersistenceMigrationOperationKind,
} from "./persistence.js";
export {
  action,
  axis,
  controlsSettings,
  defineInputMap,
  gamepad,
  keyboard,
  pointerAxis,
  pointerButton,
  touchControl,
  type IInputActionDeclaration,
  type IInputAxisDeclaration,
  type IControlsSettingsDeclaration,
  type IControlsSettingsRowDeclaration,
  type ControlsSettingsRowOptions,
  type IInputMapDeclaration,
  type IPersistedBindingOverrideDeclaration,
  type InputBinding,
} from "./input.js";
export { MeshExtendedMaterial, type ExtendedMaterialPreset, type IMeshExtendedMaterialOptions } from "./materials/MeshExtendedMaterial.js";
export { MeshStandardMaterial, type ColorValue, type IMaterialEmissiveBloomOptions, type MaterialAlphaMode, type MaterialBlendMode, type TextureSlotReference } from "./materials/MeshStandardMaterial.js";
export {
  ShaderMaterial,
  shaderBuiltin,
  shaderLiteral,
  shaderTexture,
  shaderTextureSample,
  shaderUniform,
  shaderUniformRef,
  type IShaderExpression,
  type IShaderMaterialOptions,
  type IShaderProgramOptions,
  type IShaderTextureOptions,
  type IShaderUniformOptions,
  type ShaderBuiltinInput,
  type ShaderExpressionKind,
  type ShaderLiteralValue,
  type ShaderOutput,
  type ShaderUniformType,
} from "./materials/ShaderMaterial.js";
export { Vector3, type Vector3Tuple } from "./math/Vector3.js";
export {
  staticNavigation,
  type INavigationPathQueryDeclaration,
  type INavigationRegionDeclaration,
  type IStaticNavigationDeclaration,
  type NavigationPoint2,
  type NavigationPoint3,
} from "./navigation.js";
export {
  overlay,
  type IOverlayDeclaration,
  type IOverlayMessageDeclaration,
  type IOverlayMessageSchema,
  type IOverlayMountOptions,
  type OverlayInputMode,
  type OverlayMessageSchemaKind,
  type OverlayTargetProfile,
} from "./overlay.js";
export {
  uiColorToken,
  uiComponent,
  uiComponentInstance,
  uiFontFamilyToken,
  uiGlyphPrompt,
  uiLocalization,
  uiRadiusToken,
  uiSpacingToken,
  uiTextSizeToken,
  uiTheme,
  uiToken,
  uiRecipe,
  uiToastQueue,
  uiTooltip,
  validateUiWidgetSupport,
  type IUnsupportedUiWidgetOptions,
  type IUiComponentDefinition,
  type IUiComponentInstance,
  type IUiComponentProp,
  type IUiGlyphPrompt,
  type IUiLocalization,
  type IUiRecipeOptions,
  type IUiRecipeSource,
  type IUiTheme,
  type IUiThemeToken,
  type IUiToastQueue,
  type IUiTooltip,
  type UiRecipeKind,
  type UiThemeTokenKind,
} from "./ui.js";
export {
  boxCollider,
  capsuleCollider,
  meshCollider,
  physics,
  physicsJoint,
  rigidBody,
  sphereCollider,
  type IColliderSlopeDeclaration,
  type ICcdDeclaration,
  type IColliderDeclaration,
  type IMeshColliderDeclaration,
  type IPhysicsDeclaration,
  type IPhysicsJointDeclaration,
  type IPhysicsMaterialOptions,
  type IRigidBodyDeclaration,
  type ISensorDeclaration,
  type PhysicsBodyKind,
  type PhysicsColliderKind,
  type SensorPhase,
} from "./physics.js";
export {
  PrefabModelAsset,
  PrefabTransform,
  definePrefab,
  modelActorPrefab,
  primitiveActorPrefab,
  type IModelActorPrefabOptions,
  type IPrefabDeclaration,
  type IPrimitiveActorPrefabDeclaration,
  type IPrimitiveActorPrefabOptions,
} from "./prefab.js";
export { OrthographicCamera, PerspectiveCamera } from "./scene/Camera.js";
export { ContactShadows, type IContactShadowsOptions } from "./scene/ContactShadows.js";
export { AmbientLight, DirectionalLight, PointLight, SpotLight } from "./scene/Light.js";
export { Group, type IGroupOptions } from "./scene/Group.js";
export { Mesh } from "./scene/Mesh.js";
export { Object3D, type ITransformPatch } from "./scene/Object3D.js";
export { Scene } from "./scene/Scene.js";
export { defineRuntimeConfig, type IRuntimeConfigDeclaration } from "./time.js";
