export type {
  AuthoringDiagnosticSeverity,
  IAuthoringDiagnostic,
  IAuthoringDiagnosticInput,
  IAuthoringDiagnosticRelated,
} from "./diagnostics.js";
export { authoringDiagnostic, hasAuthoringErrors, sortAuthoringDiagnostics, unsupportedOperationDiagnostic } from "./diagnostics.js";
export type { AuthoringDocumentKind, IAuthoringDocument, IReadAuthoringDocumentResult } from "./documents.js";
export {
  classifyAuthoringDocument,
  classifyAuthoringDocumentPath,
  isGeneratedArtifactPath,
  normalizeRelativePath,
  readAuthoringJsonDocument,
  writeAuthoringJsonDocument,
} from "./documents.js";
export { formatAuthoringDocument, stableAuthoringJson } from "./format.js";
export type {
  IScriptReference,
  ISceneDocument,
  ISceneEntity,
  IScenePrefab,
  ISceneResource,
  ISceneSystem,
  ISceneTransform,
  ISceneUi,
  ISceneUiBinding,
  ISceneUiNode,
  IAssetDeclaration,
  IAssetDocument,
  IAudioDocument,
  IAudioSoundDeclaration,
  IInputActionDeclaration,
  IInputDocument,
  IMaterialDeclaration,
  IMaterialDocument,
  IMeshDeclaration,
  IMeshDocument,
  IPrefabDocument,
  ISystemsDocument,
  IUiDocument,
} from "./schemas.js";
export {
  assetDocumentSchema,
  audioDocumentSchema,
  environmentDocumentSchema,
  inputDocumentSchema,
  logicalIdPattern,
  materialDocumentSchema,
  meshDocumentSchema,
  prefabDocumentSchema,
  projectDocumentSchema,
  runtimeDocumentSchema,
  sceneDocumentSchema,
  systemsDocumentSchema,
  uiDocumentSchema,
} from "./schemas.js";
export type { IAuthoringProject, ILoadAuthoringProjectOptions } from "./project.js";
export { discoverAuthoringFiles, loadAuthoringProject } from "./project.js";
export type {
  BundleImportMode,
  IImportBundleOptions,
  IImportBundleResult,
  IImportedBundleArtifact,
  ISkippedBundleArtifact,
} from "./importBundle.js";
export { importBundle } from "./importBundle.js";
export type {
  IAuthoringOperationContext,
  IAuthoringOperationResult,
  IAddEntityOptions,
  IAddAssetOptions,
  IAddAnimationClipOptions,
  IAddAnimationGraphStateOptions,
  IAddAudioSoundOptions,
  IAddGroupOptions,
  IAddPrefabOptions,
  IAddResourceOptions,
  IAddTagOptions,
  IAddUiNodeOptions,
  IAttachScriptOptions,
  IAttachSystemScriptOptions,
  IBindUiOptions,
  IBindUiDocumentOptions,
  ICreateSceneOptions,
  ICreateSceneResult,
  ICreateAudioDocumentOptions,
  ICreateEnvironmentDocumentOptions,
  ICreateMaterialOptions,
  ICreateMeshPrimitiveOptions,
  ICreateMeshCustomOptions,
  ICreatePrefabDocumentOptions,
  ICreateProjectMetadataOptions,
  ICreateRuntimeConfigOptions,
  ICreateSystemOptions,
  ICreateUiDocumentOptions,
  IAddInputActionOptions,
  IAddInputAxisOptions,
  IAddUiNodeDocumentOptions,
  IAddPrefabComponentOptions,
  IAddParticleEmitterOptions,
  IAddUiTextOptions,
  IImportWorldOptions,
  IImportWorldResult,
  IInspectSceneResult,
  IRemoveComponentOptions,
  ISceneInspection,
  ISetCameraOptions,
  ISetCameraComponentOptions,
  ISetCharacterControllerComponentOptions,
  ISetColliderComponentOptions,
  ISetComponentOptions,
  ISetEnvironmentMapOptions,
  ISetEnvironmentSkyboxOptions,
  ISetEnvironmentTerrainOptions,
  ISetLightComponentOptions,
  ISetMaterialOptions,
  ISetMeshRendererComponentOptions,
  ISetRenderLayersComponentOptions,
  ISetPrefabOptions,
  ISetPrefabColorOptions,
  ISetRigidBodyComponentOptions,
  IAddResourceDocumentEntryOptions,
  ICreateResourcesDocumentOptions,
  ISetResourceDocumentEntryOptions,
  ISetResourceOptions,
  ISetRuntimeRenderingOptions,
  ISetRuntimeWindowOptions,
  ISetSceneLifecycleOptions,
  ISetSystemMetadataOptions,
  ISetTransformOptions,
  ISetUiLayoutOptions,
  ISetUiStyleOptions,
  ISetVisibilityComponentOptions,
  IValidateAuthoringProjectOptions,
  IValidateSceneOptions,
} from "./operations.js";
export {
  addEntity,
  addAsset,
  addAnimationClip,
  addAnimationGraphState,
  addAudioSound,
  addGroup,
  addPrefab,
  addInputAction,
  addInputAxis,
  addUiNodeDocument,
  addPrefabComponent,
  addParticleEmitter,
  addResource,
  addResourceDocumentEntry,
  addTag,
  addUiText,
  addUiNode,
  attachScript,
  attachSystemScript,
  authoringOperationResult,
  bindUi,
  bindUiDocument,
  createAudioDocument,
  createEnvironmentDocument,
  createMaterial,
  createMeshCustom,
  createMeshPrimitive,
  createPrefabDocument,
  createProjectMetadata,
  createRuntimeConfig,
  createResourcesDocument,
  createScene,
  createSystem,
  createUiDocument,
  importWorld,
  inspectScene,
  loadProjectForOperation,
  removeComponent,
  setCamera,
  setCameraComponent,
  setCharacterControllerComponent,
  setColliderComponent,
  setComponent,
  setEnvironmentMap,
  setEnvironmentSkybox,
  setEnvironmentTerrain,
  setLightComponent,
  setMaterial,
  setMeshRendererComponent,
  setPrefab,
  setPrefabColor,
  setRenderLayersComponent,
  setRigidBodyComponent,
  setResource,
  setResourceDocumentEntry,
  setRuntimeRendering,
  setRuntimeWindow,
  setSceneLifecycle,
  setSystemMetadata,
  setTransform,
  setUiLayout,
  setUiStyle,
  setVisibilityComponent,
  validateScene,
  validateAuthoringProject,
  writeChangedProjectDocuments,
} from "./operations.js";
export type {
  AuthoringOperationName,
  AuthoringOperationPathPolicy,
  AuthoringOperationResultShape,
  AuthoringOperationSourceFamily,
  IAuthoringOperationArgumentDescriptor,
  IAuthoringOperationDescriptor,
  IDispatchAuthoringOperationOptions,
} from "./operationRegistry.js";
export {
  AUTHORING_OPERATION_NAMES,
  AUTHORING_OPERATION_REGISTRY,
  dispatchAuthoringOperation,
  getAuthoringOperationDescriptor,
  listAuthoringOperationDescriptors,
} from "./operationRegistry.js";
