export type {
  AuthoringDiagnosticSeverity,
  IAuthoringDiagnostic,
  IAuthoringDiagnosticFix,
  IAuthoringDiagnosticInput,
  IAuthoringDiagnosticRelated,
} from "./diagnostics.js";
export { authoringDiagnostic, hasAuthoringErrors, sortAuthoringDiagnostics, unsupportedOperationDiagnostic } from "./diagnostics.js";
export type {
  IApplyAuthoringBatchOptions,
  IAuthoringBatchApplyResult,
  IAuthoringBatchDocument,
  IAuthoringBatchFilePlan,
  IAuthoringBatchOperation,
  IAuthoringBatchOperationTrace,
  IAuthoringBatchPlanResult,
  IPlanAuthoringBatchOptions,
} from "./batches.js";
export {
  applyAuthoringBatch,
  AUTHORING_BATCH_SCHEMA,
  AUTHORING_BATCH_VERSION,
  planAuthoringBatch,
} from "./batches.js";
export type {
  IGeneratorOwnerAuthorization,
  IGeneratorOutputOwner,
  IGeneratorProvenanceIndex,
} from "./generatorProvenance.js";
export {
  advanceGeneratorOutputHash,
  generatedOutputOwnershipDiagnostic,
  hashGeneratorOutputs,
  resolveGeneratorProvenance,
} from "./generatorProvenance.js";
export type {
  AuthoringTransactionHash,
  IAuthoringTransactionFaultInjection,
  IAuthoringTransactionFile,
  IAuthoringTransactionResult,
  IPublishAuthoringTransactionOptions,
  IRecoverAuthoringTransactionsOptions,
} from "./transactionJournal.js";
export {
  hashAuthoringTransactionBytes,
  publishAuthoringTransaction,
  recoverAuthoringTransactions,
} from "./transactionJournal.js";
export type { IPrescriptiveDiagnosticCode } from "./prescriptiveCodes.js";
export { PRESCRIPTIVE_DIAGNOSTIC_CODES, prescriptiveFixForCode } from "./prescriptiveCodes.js";
export type { IWorldBiomeDefinition, WorldBiomeId } from "./biomes.js";
export { WORLD_BIOMES, WORLD_BIOME_IDS, isWorldBiomeId } from "./biomes.js";
export type { AuthoringDocumentKind, IAuthoringDocument, IAuthoringDocumentSourceMap, IReadAuthoringDocumentResult } from "./documents.js";
export {
  classifyAuthoringDocument,
  classifyAuthoringDocumentPath,
  isGeneratedArtifactPath,
  normalizeRelativePath,
  readAuthoringJsonDocument,
  writeAuthoringJsonDocument,
} from "./documents.js";
export { formatAuthoringDocument, stableAuthoringJson } from "./format.js";
export { expandRegistryDocumentPreset, listRegistryDocumentPresetIds, type RegistryDocumentPresetId } from "./documentPresets.js";
export { expandPlacementSet, expandPlacementSets, setDottedPath, type IExpandedPlacementInstance } from "./placementSets.js";
export type {
  IScriptReference,
  ISceneDocument,
  ISceneEntity,
  IScenePrefabInstance,
  IScenePlacementSet,
  ScenePlacementPattern,
  IScenePrefab,
  ISceneResource,
  ISceneSystem,
  ISceneTransform,
  ISceneUi,
  ISceneUiBinding,
  ISceneUiNode,
  IAssetDeclaration,
  IAssetDocument,
  IAudioDocument,
  IAudioSoundDeclaration,
  IInputActionDeclaration,
  IInputControlsSettings,
  IInputControlsSettingsRow,
  IInputDocument,
  IInputPersistedBindingOverride,
  IMaterialDeclaration,
  IMaterialDocument,
  IMeshDeclaration,
  IMeshDocument,
  IPrefabDocument,
  ISchemaDocument,
  ISchemaEntry,
  ISchemaField,
  ISystemsDocument,
  ISystemCountdown,
  IUiDocument,
} from "./schemas.js";
export {
  assetDocumentSchema,
  audioDocumentSchema,
  environmentDocumentSchema,
  flowDocumentSchema,
  generatorDocumentSchema,
  inputDocumentSchema,
  logicalIdPattern,
  materialDocumentSchema,
  meshDocumentSchema,
  prefabDocumentSchema,
  projectDocumentSchema,
  runtimeDocumentSchema,
  schemaDocumentSchema,
  sceneDocumentSchema,
  sequenceDocumentSchema,
  supportedPrefabPrimitives,
  systemsDocumentSchema,
  targetProfileDocumentSchema,
  uiDocumentSchema,
} from "./schemas.js";
export type { IAuthoringProject, ILoadAuthoringProjectOptions } from "./project.js";
export { discoverAuthoringFiles, loadAuthoringProject } from "./project.js";
export type {
  BundleImportMode,
  IImportBundleOptions,
  IImportBundleResult,
  IImportedBundleArtifact,
  ISkippedBundleArtifact,
} from "./importBundle.js";
export { importBundle } from "./importBundle.js";
export type {
  AuthoringRecipeId,
  IApplyAuthoringRecipeOptions,
  IAuthoringRecipeApplyResult,
  IAuthoringRecipeArgumentDescriptor,
  IAuthoringRecipeComposition,
  IAuthoringRecipeDescriptor,
  IAuthoringRecipeOperation,
  IAuthoringRecipeOperationResult,
  IAuthoringRecipePlanOptions,
  IAuthoringRecipePlanResult,
} from "./recipes.js";
export {
  applyAuthoringRecipe,
  getAuthoringRecipeDescriptor,
  listAuthoringRecipeDescriptors,
  listAuthoringRecipeIds,
  planAuthoringRecipe,
} from "./recipes.js";
export type {
  ActorArchetypeId,
  IActorArchetypeDescriptor,
  IApplyActorArchetypeOptions,
  IUpdateActorArchetypeOptions,
} from "./archetypes.js";
export { applyActorArchetype, listActorArchetypes, updateActorArchetype } from "./archetypes.js";
export type {
  GameAssetAudioSourcingStatus,
  GameAssetAudioSurfaceId,
  GameEvidenceKind,
  GameProductionCommandStatus,
  GameProductionMode,
  GameProviderProbeStatus,
  GameReleaseRiskSeverity,
  GameUiStateId,
  GameVisualScorecardCategoryId,
  GameWorkflowPhaseId,
  GameWorkflowPhaseStatus,
  IGameAssetAudioLedgerEntry,
  IGameProductionCommand,
  IGameProviderProbe,
  IGameReleaseRisk,
  IGameUiStateCoverage,
  IGameVisualScorecardCategory,
  IGameWorkflowDiagnostic,
  IGameWorkflowEvidence,
  IGameWorkflowPhaseLedger,
  IGameWorkflowReport,
} from "./gameWorkflow.js";
export {
  createGameQualityReport,
  GAME_ASSET_AUDIO_SURFACE_IDS,
  GAME_UI_STATE_IDS,
  GAME_VISUAL_SCORECARD_CATEGORY_IDS,
  GAME_WORKFLOW_PHASE_IDS,
  GAME_WORKFLOW_REPORT_SCHEMA,
  GAME_WORKFLOW_REPORT_VERSION,
  probeGameAssetProviders,
  readGameQualityReport,
  validateGameQualityReport,
} from "./gameWorkflow.js";
export type {
  GameAgentProjectKind,
  ICreateGameAgentInventoryOptions,
  IGameAgentAssetSummary,
  IGameAgentHighValueSurface,
  IGameAgentInputSummary,
  IGameAgentInventory,
  IGameAgentMaterialSummary,
  IGameAgentNormalizedMetadata,
  IGameAgentProductionSummary,
  IGameAgentSceneSummary,
  IGameAgentScriptReference,
  IGameAgentScriptSystem,
  IGameAgentSourceFamily,
  IGameAgentUiSummary,
} from "./gameAgentInventory.js";
export {
  createGameAgentInventory,
  GAME_AGENT_INVENTORY_SCHEMA,
  GAME_AGENT_INVENTORY_VERSION,
} from "./gameAgentInventory.js";
export type {
  IIterateDiagnostic,
  IIterateReport,
  IIterateStepReport,
  IterateStepStatus,
} from "./iterateReport.js";
export {
  ITERATE_REPORT_SCHEMA,
  ITERATE_REPORT_VERSION,
  validateIterateReport,
} from "./iterateReport.js";
export type {
  IAuthoringOperationContext,
  IAuthoringOperationResult,
  IAddEntityOptions,
  IAddPrefabInstanceOptions,
  IAddPrefabInstancesOptions,
  IAddTenPinLayoutOptions,
  IAddAssetOptions,
  IAddAnimationClipOptions,
  IAddAnimationGraphStateOptions,
  IAddAudioSoundOptions,
  IAddGroupOptions,
  IAddPrefabOptions,
  IAddResourceOptions,
  IAddTagOptions,
  IAddUiNodeOptions,
  IAttachScriptOptions,
  IAttachSystemScriptOptions,
  IBindUiOptions,
  IBindUiDocumentOptions,
  ICreateSceneOptions,
  ICreateSceneResult,
  ICreateAudioDocumentOptions,
  ICreateEnvironmentDocumentOptions,
  ICreateMaterialOptions,
  ICreateMeshPrimitiveOptions,
  ICreateMeshCustomOptions,
  ICreatePrefabDocumentOptions,
  ICreateProjectMetadataOptions,
  ICreateRuntimeConfigOptions,
  ICreateSystemOptions,
  ICreateUiDocumentOptions,
  IRecordGeneratorProvenanceOptions,
  IAddInputActionOptions,
  IAddInputAxisOptions,
  ISetInputBindingOverrideOptions,
  ISetInputControlsOptions,
  IAddUiComponentInstanceOptions,
  IApplyUiRecipeOptions,
  IRemoveUiComponentInstanceOptions,
  IAddUiNodeDocumentOptions,
  IAddPrefabComponentOptions,
  IAddParticleEmitterOptions,
  IAddUiTextOptions,
  IAddEnvironmentScatterLayerOptions,
  IImportWorldOptions,
  IImportWorldResult,
  IInspectSceneResult,
  IRemoveComponentOptions,
  IRemoveEntityOptions,
  IRemoveResourceOptions,
  IRemoveUiNodeOptions,
  ISceneInspection,
  ISetCameraOptions,
  ISetCameraComponentOptions,
  ISetCharacterControllerComponentOptions,
  ISetColliderComponentOptions,
  ISetComponentOptions,
  ISetEnvironmentMapOptions,
  ISetEnvironmentPathOptions,
  ISetEnvironmentSkyboxOptions,
  ISetEnvironmentSourceAssetLodOptions,
  ISetEnvironmentTerrainOptions,
  ISetEnvironmentVolumetricsOptions,
  ISetEnvironmentWalkabilityOptions,
  ISetLightComponentOptions,
  ISetMaterialOptions,
  ISetMeshRendererComponentOptions,
  ISetPrefabMaterialOptions,
  ISetRenderLayersComponentOptions,
  ISetPrefabOptions,
  ISetPrefabColorOptions,
  ISetRigidBodyComponentOptions,
  IAddResourceDocumentEntryOptions,
  ICreateResourcesDocumentOptions,
  ICreateSchemaDocumentOptions,
  ISetResourceDocumentEntryOptions,
  ISetResourceOptions,
  ICreateFlowDocumentOptions,
  IAddFlowStateOptions,
  IAddFlowTransitionOptions,
  ICreateSequenceDocumentOptions,
  IAddSequenceTrackOptions,
  IAddSequenceKeyOptions,
  ISetRuntimeRenderingOptions,
  ISetRuntimeWindowOptions,
  ISetSchemaEntryOptions,
  ISetSceneLifecycleOptions,
  ISetSpawnerComponentOptions,
  ISetSystemMetadataOptions,
  ISetTargetProfileOptions,
  ISetTransformOptions,
  ISetUiLayoutOptions,
  ISetUiStyleOptions,
  ISetVisibilityComponentOptions,
  IValidateAuthoringProjectOptions,
  IValidateSceneOptions,
} from "./operations.js";
export {
  addEntity,
  addPrefabInstance,
  addPrefabInstances,
  addTenPinLayout,
  addAsset,
  addAnimationClip,
  addAnimationGraphState,
  addAudioSound,
  addGroup,
  addPrefab,
  addInputAction,
  addInputAxis,
  addUiComponentInstance,
  applyUiRecipe,
  removeUiComponentInstance,
  removeEntity,
  removeResource,
  removeUiNode,
  addUiNodeDocument,
  addPrefabComponent,
  addParticleEmitter,
  addResource,
  addResourceDocumentEntry,
  addTag,
  addUiText,
  addUiNode,
  attachScript,
  attachSystemScript,
  authoringOperationResult,
  bindUi,
  bindUiDocument,
  addFlowState,
  addFlowTransition,
  addSequenceKey,
  addSequenceTrack,
  createAudioDocument,
  createEnvironmentDocument,
  createFlowDocument,
  createMaterial,
  createMeshCustom,
  createMeshPrimitive,
  createPrefabDocument,
  createProjectMetadata,
  createRuntimeConfig,
  createResourcesDocument,
  createSchemaDocument,
  createScene,
  createSequenceDocument,
  createSystem,
  createUiDocument,
  importWorld,
  inspectScene,
  loadProjectForOperation,
  recordGeneratorProvenance,
  recordBlenderGenerator,
  removeComponent,
  setCamera,
  setCameraComponent,
  setCharacterControllerComponent,
  setColliderComponent,
  setComponent,
  addEnvironmentScatterLayer,
  setEnvironmentLightProbe,
  setEnvironmentMap,
  setEnvironmentPath,
  setEnvironmentSkybox,
  setEnvironmentSourceAssetLod,
  setEnvironmentTerrain,
  setEnvironmentVolumetrics,
  setEnvironmentWalkability,
  setInputBindingOverride,
  setInputControls,
  setLightComponent,
  setMaterial,
  setMeshRendererComponent,
  setPrefabMaterial,
  setPrefab,
  setPrefabColor,
  setRenderLayersComponent,
  setRigidBodyComponent,
  setResource,
  setResourceDocumentEntry,
  setRuntimeRendering,
  setRuntimeWindow,
  setSchemaEntry,
  setSceneLifecycle,
  setSpawnerComponent,
  setSystemMetadata,
  setTargetProfile,
  setTransform,
  setUiLayout,
  setUiStyle,
  setVisibilityComponent,
  validateScene,
  validateAuthoringProject,
  writeChangedProjectDocuments,
} from "./operations.js";
export type {
  AuthoringOperationName,
  AuthoringOperationMutationPolicy,
  AuthoringOperationPathPolicy,
  AuthoringOperationResultShape,
  AuthoringOperationSourceFamily,
  IAuthoringOperationArgumentDescriptor,
  IAuthoringOperationAdapterExclusion,
  IAuthoringOperationAdapterExclusions,
  IAuthoringOperationCliAdapterDescriptor,
  IAuthoringOperationCliArgumentBinding,
  IAuthoringOperationDescriptor,
  IAuthoringOperationTargetContext,
  AuthoringOperationTargetResolver,
  IAuthoringOperationEditorAdapterDescriptor,
  IAuthoringOperationEditorSmokeDescriptor,
  IDispatchAuthoringOperationOptions,
} from "./operationRegistry.js";
export {
  AUTHORING_OPERATION_NAMES,
  AUTHORING_OPERATION_REGISTRY,
  buildAuthoringOperationCliArgv,
  dispatchAuthoringOperation,
  getAuthoringOperationDescriptor,
  listAuthoringOperationDescriptors,
  renderAuthoringOperationCliUsage,
} from "./operationRegistry.js";
