import type { ScriptContext, ScriptEntity } from "@threenative/script-stdlib";

// Generated by ThreeNative. Do not edit.

export type ProjectEntityId = "camera.main" | "ground" | "light.key" | "projectile" | "projectile.fast" | "wall" | "wall/piece.000" | "wall/piece.001" | "wall/piece.002" | "wall/piece.003";
export type ProjectEventId = string;
export type ProjectInputId = "MoveX" | "MoveZ" | "move-left" | "move-right" | "retry";
export type ProjectMaterialId = "mat.ground" | "mat.projectile" | "mat.wall";
export type ProjectPrefabId = "prefab.target-block";
export type ProjectResourceId = "ActiveCamera" | "DestructionState";
export type ProjectSceneId = "arena";
export type ProjectUiId = string;

export interface ProjectComponentMap {
  "Camera": { [key: string]: unknown };
  "Collider": { [key: string]: unknown };
  "Destructible": { [key: string]: unknown };
  "Light": { [key: string]: unknown };
  "MeshRenderer": { [key: string]: unknown };
  "RigidBody": { [key: string]: unknown };
  "Transform": { [key: string]: unknown };
}

export interface ProjectResourceMap {
}

export interface ProjectEventMap {
}
export type ProjectResourceValue<K extends ProjectResourceId> = K extends keyof ProjectResourceMap ? ProjectResourceMap[K] : unknown;
export type ProjectResourcePatch<K extends ProjectResourceId> = ProjectResourceValue<K> extends Record<string, unknown> ? Partial<ProjectResourceValue<K>> : Record<string, unknown>;

export interface ProjectGameToOverlayMessageMap {
}

export interface ProjectOverlayToGameMessageMap {
}

export interface ProjectScriptEntity extends ScriptEntity {
  get<K extends keyof ProjectComponentMap>(component: K): ProjectComponentMap[K];
  get<K extends keyof ProjectComponentMap, T extends Record<string, unknown>>(component: K, defaults: T): ProjectComponentMap[K] & T;
  patch<K extends keyof ProjectComponentMap>(component: K, value: Partial<ProjectComponentMap[K]>): void;
  set<K extends keyof ProjectComponentMap>(component: K, value: ProjectComponentMap[K]): void;
}

export interface ProjectContext extends Omit<ScriptContext, "entity" | "input" | "query" | "resources"> {
  entity(id: ProjectEntityId): ProjectScriptEntity | undefined;
  input: Omit<ScriptContext["input"], "action" | "axis" | "getAxis" | "getAxis2" | "getButton" | "getButtonDown" | "getButtonUp" | "pressed" | "released"> & {
    action(name: ProjectInputId): boolean;
    axis(name: ProjectInputId): number;
    getAxis(axis: ProjectInputId): number;
    getAxis2(xAxis: ProjectInputId, yAxis: ProjectInputId, options?: { deadzone?: number; normalize?: boolean }): [number, number];
    getButton(name: ProjectInputId): boolean;
    getButtonDown(name: ProjectInputId): boolean;
    getButtonUp(name: ProjectInputId): boolean;
    pressed(name: ProjectInputId): boolean;
    released(name: ProjectInputId): boolean;
  };
  query(query?: Parameters<ScriptContext["query"]>[0]): ProjectScriptEntity[];
  resources: Omit<ScriptContext["resources"], "get" | "patch" | "set"> & {
    get<K extends ProjectResourceId>(name: K): ProjectResourceValue<K>;
    get<K extends ProjectResourceId, T extends Record<string, unknown>>(name: K, defaults: T): ProjectResourceValue<K> & T;
    patch<K extends ProjectResourceId>(name: K, value: ProjectResourcePatch<K>): void;
    set<K extends ProjectResourceId>(name: K, value: ProjectResourceValue<K>): void;
  };
}
