import type { ICompilerDiagnostic } from "../diagnostics.js";
import { diagnosePortableSystem } from "./diagnostics.js";

export interface ISystemScriptSource {
  name: string;
  script?: {
    exportName: string;
    source: string;
  };
}

export interface IScriptBundleResult {
  code?: string;
  diagnostics: ICompilerDiagnostic[];
}

export function bundleSystemScripts(systems: ReadonlyArray<ISystemScriptSource>): IScriptBundleResult {
  const scriptedSystems = systems
    .filter((system): system is ISystemScriptSource & { script: NonNullable<ISystemScriptSource["script"]> } => system.script !== undefined)
    .sort((left, right) => left.name.localeCompare(right.name));

  const diagnostics = scriptedSystems.flatMap((system) =>
    diagnosePortableSystem({
      source: system.script.source,
      systemName: system.name,
    }),
  );
  if (diagnostics.length > 0 || scriptedSystems.length === 0) {
    return { diagnostics };
  }

  const declarations = scriptedSystems.map((system) => `const ${system.script.exportName} = ${normalizeSystemSource(system.script.source)};`);
  const exports = scriptedSystems.map((system) => `  ${JSON.stringify(system.script.exportName)}: ${system.script.exportName},`);
  return {
    diagnostics: [],
    code: [
      "// Generated by ThreeNative. Do not edit.",
      ...declarations,
      "export const systems = Object.freeze({",
      ...exports,
      "});",
      "",
    ].join("\n"),
  };
}

function normalizeSystemSource(source: string): string {
  if (/^async\s+[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return source.replace(/^async\s+/, "async function ");
  }
  if (/^[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return `function ${source}`;
  }
  return source;
}
