import type { ICompilerDiagnostic } from "../diagnostics.js";
import { diagnosePortableSystem } from "./diagnostics.js";

export interface ISystemScriptSource {
  commands?: ReadonlyArray<{ kind: string }>;
  eventReads?: ReadonlyArray<string>;
  eventWrites?: ReadonlyArray<string>;
  name: string;
  queries?: ReadonlyArray<{ with: string[]; without: string[] }>;
  reads?: ReadonlyArray<string>;
  resourceReads?: ReadonlyArray<string>;
  resourceWrites?: ReadonlyArray<string>;
  script?: {
    exportName: string;
    source: string;
  };
  services?: ReadonlyArray<string>;
  writes?: ReadonlyArray<string>;
}

export interface IScriptBundleResult {
  code?: string;
  diagnostics: ICompilerDiagnostic[];
}

export function bundleSystemScripts(systems: ReadonlyArray<ISystemScriptSource>): IScriptBundleResult {
  const scriptedSystems = systems
    .filter((system): system is ISystemScriptSource & { script: NonNullable<ISystemScriptSource["script"]> } => system.script !== undefined)
    .sort((left, right) => left.name.localeCompare(right.name));

  const diagnostics = scriptedSystems.flatMap((system) =>
    diagnosePortableSystem({
      commands: system.commands?.map((command) => command.kind),
      eventWrites: system.eventWrites,
      queries: system.queries,
      resourceWrites: system.resourceWrites,
      services: system.services,
      source: system.script.source,
      systemName: system.name,
      writes: system.writes,
    }),
  );
  if (diagnostics.length > 0 || scriptedSystems.length === 0) {
    return { diagnostics };
  }

  const handles = scriptHandleNames(scriptedSystems).map((name) => `const ${name} = Object.freeze({ name: ${JSON.stringify(name)} });`);
  const declarations = scriptedSystems.map((system) => `const ${system.script.exportName} = ${normalizeSystemSource(system.script.source)};`);
  const exports = scriptedSystems.map((system) => `  ${JSON.stringify(system.script.exportName)}: ${system.script.exportName},`);
  const systemIds = scriptedSystems.map((system) => `  ${JSON.stringify(system.script.exportName)}: ${JSON.stringify(system.name)},`);
  return {
    diagnostics: [],
    code: [
      "// Generated by ThreeNative. Do not edit.",
      ...handles,
      ...declarations,
      "export const systemIds = Object.freeze({",
      ...systemIds,
      "});",
      "export const systems = Object.freeze({",
      ...exports,
      "});",
      "",
    ].join("\n"),
  };
}

function scriptHandleNames(systems: ReadonlyArray<ISystemScriptSource>): string[] {
  const names = new Set<string>();
  for (const system of systems) {
    for (const name of [
      ...(system.reads ?? []),
      ...(system.writes ?? []),
      ...(system.eventReads ?? []),
      ...(system.eventWrites ?? []),
      ...(system.resourceReads ?? []),
      ...(system.resourceWrites ?? []),
      ...(system.queries ?? []).flatMap((query) => [...query.with, ...query.without]),
    ]) {
      if (/^[A-Za-z_$][\w$]*$/.test(name)) {
        names.add(name);
      }
    }
  }
  return [...names].sort();
}

function normalizeSystemSource(source: string): string {
  if (/^async\s+[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return source.replace(/^async\s+/, "async function ");
  }
  if (/^[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return `function ${source}`;
  }
  return source;
}
