import type { ICompilerDiagnostic } from "../diagnostics.js";
import { diagnosePortableSystem } from "./diagnostics.js";

export interface ISystemScriptSource {
  commands?: ReadonlyArray<{ kind: string }>;
  eventReads?: ReadonlyArray<string>;
  eventWrites?: ReadonlyArray<string>;
  name: string;
  queries?: ReadonlyArray<{ with: string[]; without: string[] }>;
  reads?: ReadonlyArray<string>;
  resourceReads?: ReadonlyArray<string>;
  resourceWrites?: ReadonlyArray<string>;
  script?: {
    exportName: string;
    source?: string;
    sourceRef?: {
      export: string;
      hash?: string;
      module: string;
      systemId: string;
    };
  };
  services?: ReadonlyArray<string>;
  writes?: ReadonlyArray<string>;
}

export interface IScriptBundleResult {
  code?: string;
  diagnostics: ICompilerDiagnostic[];
  manifest?: IScriptsManifest;
}

export interface IScriptsManifest {
  artifacts: Array<{
    generated: true;
    path: "scripts.bundle.js";
    source: false;
  }>;
  schema: "threenative.scripts";
  systems: Array<{
    generated: {
      bundle: "scripts.bundle.js";
      exportName: string;
    };
    source?: {
      export: string;
      hash?: string;
      module: string;
    };
    systemId: string;
  }>;
  version: "0.1.0";
}

export function bundleSystemScripts(systems: ReadonlyArray<ISystemScriptSource>): IScriptBundleResult {
  const scriptedSystems = systems
    .filter((system): system is ISystemScriptSource & { script: NonNullable<ISystemScriptSource["script"]> } => system.script !== undefined)
    .sort((left, right) => left.name.localeCompare(right.name));

  const unresolvedSourceDiagnostics = scriptedSystems.flatMap((system): ICompilerDiagnostic[] =>
    system.script.source === undefined && system.script.sourceRef !== undefined
      ? [
          {
            code: "TN_SCRIPT_SOURCE_REFERENCE_UNRESOLVED",
            file: system.script.sourceRef.module,
            message: `System '${system.name}' references script export '${system.script.sourceRef.export}' before it has been bundled.`,
            path: `systems/${system.name}/script/sourceRef`,
            severity: "error",
            suggestion: "Resolve the referenced TypeScript module/export into the generated scripts bundle before emitting runtime IR.",
          },
        ]
      : [],
  );
  const exportCollisionDiagnostics = diagnoseExportNameCollisions(scriptedSystems);
  const diagnostics = [
    ...exportCollisionDiagnostics,
    ...unresolvedSourceDiagnostics,
    ...scriptedSystems.flatMap((system) =>
      system.script.source === undefined
        ? []
        : diagnosePortableSystem({
            commands: system.commands?.map((command) => command.kind),
            eventWrites: system.eventWrites,
            exportName: system.script.sourceRef?.export,
            file: system.script.sourceRef?.module,
            queries: system.queries,
            resourceWrites: system.resourceWrites,
            services: system.services,
            source: system.script.source,
            systemName: system.name,
            writes: system.writes,
          }),
    ),
  ];
  if (diagnostics.length > 0 || scriptedSystems.length === 0) {
    return { diagnostics };
  }

  const handles = scriptHandleNames(scriptedSystems).map((name) => `const ${name} = Object.freeze({ name: ${JSON.stringify(name)} });`);
  const declarations = scriptedSystems.map((system) => `const ${system.script.exportName} = ${normalizeSystemSource(system.script.source ?? "")};`);
  const exports = scriptedSystems.map((system) => `  ${JSON.stringify(system.script.exportName)}: ${system.script.exportName},`);
  const systemIds = scriptedSystems.map((system) => `  ${JSON.stringify(system.script.exportName)}: ${JSON.stringify(system.name)},`);
  return {
    diagnostics: [],
    manifest: scriptsManifest(scriptedSystems),
    code: [
      "// Generated by ThreeNative. Do not edit.",
      ...handles,
      ...declarations,
      "export const systemIds = Object.freeze({",
      ...systemIds,
      "});",
      "export const systems = Object.freeze({",
      ...exports,
      "});",
      "",
    ].join("\n"),
  };
}

function diagnoseExportNameCollisions(systems: ReadonlyArray<ISystemScriptSource & { script: NonNullable<ISystemScriptSource["script"]> }>): ICompilerDiagnostic[] {
  const byExport = new Map<string, string[]>();
  for (const system of systems) {
    byExport.set(system.script.exportName, [...(byExport.get(system.script.exportName) ?? []), system.name].sort());
  }
  return [...byExport.entries()].flatMap(([exportName, systemNames]) =>
    systemNames.length < 2
      ? []
      : systemNames.map((systemName) => ({
          code: "TN_SCRIPT_EXPORT_COLLISION",
          message: `System '${systemName}' generated script export '${exportName}' collides with another system.`,
          path: `systems/${systemName}/script/exportName`,
          severity: "error" as const,
          suggestion: "Rename one of the systems so generated script export names are unique after sanitization.",
        })),
  );
}

function scriptsManifest(systems: ReadonlyArray<ISystemScriptSource & { script: NonNullable<ISystemScriptSource["script"]> }>): IScriptsManifest {
  return {
    artifacts: [
      {
        generated: true,
        path: "scripts.bundle.js",
        source: false,
      },
    ],
    schema: "threenative.scripts",
    systems: systems.map((system) => ({
      generated: {
        bundle: "scripts.bundle.js",
        exportName: system.script.exportName,
      },
      ...(system.script.sourceRef === undefined
        ? {}
        : {
            source: {
              export: system.script.sourceRef.export,
              ...(system.script.sourceRef.hash === undefined ? {} : { hash: system.script.sourceRef.hash }),
              module: system.script.sourceRef.module,
            },
          }),
      systemId: system.name,
    })),
    version: "0.1.0",
  };
}

function scriptHandleNames(systems: ReadonlyArray<ISystemScriptSource>): string[] {
  const names = new Set<string>();
  for (const system of systems) {
    for (const name of [
      ...(system.reads ?? []),
      ...(system.writes ?? []),
      ...(system.eventReads ?? []),
      ...(system.eventWrites ?? []),
      ...(system.resourceReads ?? []),
      ...(system.resourceWrites ?? []),
      ...(system.queries ?? []).flatMap((query) => [...query.with, ...query.without]),
    ]) {
      if (/^[A-Za-z_$][\w$]*$/.test(name)) {
        names.add(name);
      }
    }
  }
  return [...names].sort();
}

function normalizeSystemSource(source: string): string {
  if (/^async\s+[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return source.replace(/^async\s+/, "async function ");
  }
  if (/^[A-Za-z_$][\w$]*\s*\(/.test(source)) {
    return `function ${source}`;
  }
  return source;
}
