import type { ScriptContext, ScriptEntity } from "@threenative/script-stdlib";

// Generated by ThreeNative. Do not edit.

export type ProjectEntityId = "camera.main" | "light.ambient" | "light.sun" | "stylized-nature-patch";
export type ProjectInputId = string;
export type ProjectMaterialId = string;
export type ProjectPrefabId = string;
export type ProjectResourceId = string;
export type ProjectSceneId = "stylized.nature.component.scene";
export type ProjectUiId = string;

export interface ProjectComponentMap {
}

export interface ProjectResourceMap {
}

export interface ProjectScriptEntity extends ScriptEntity {
  get<K extends keyof ProjectComponentMap>(component: K): ProjectComponentMap[K];
  get<K extends keyof ProjectComponentMap, T extends Record<string, unknown>>(component: K, defaults: T): ProjectComponentMap[K] & T;
  patch<K extends keyof ProjectComponentMap>(component: K, value: Partial<ProjectComponentMap[K]>): void;
  set<K extends keyof ProjectComponentMap>(component: K, value: ProjectComponentMap[K]): void;
}

export interface ProjectContext extends ScriptContext {
  entity(id: ProjectEntityId): ProjectScriptEntity | undefined;
  input: ScriptContext["input"] & {
    action(name: ProjectInputId): boolean;
    axis(name: ProjectInputId): number;
    getAxis(axis: ProjectInputId): number;
    getButton(name: ProjectInputId): boolean;
    getButtonDown(name: ProjectInputId): boolean;
    getButtonUp(name: ProjectInputId): boolean;
  };
  query(query?: Parameters<ScriptContext["query"]>[0]): ProjectScriptEntity[];
  resources: ScriptContext["resources"] & {
    get<K extends keyof ProjectResourceMap>(name: K): ProjectResourceMap[K];
    get<K extends keyof ProjectResourceMap, T extends Record<string, unknown>>(name: K, defaults: T): ProjectResourceMap[K] & T;
    patch<K extends keyof ProjectResourceMap>(name: K, value: Partial<ProjectResourceMap[K]>): void;
    set<K extends keyof ProjectResourceMap>(name: K, value: ProjectResourceMap[K]): void;
  };
}
