import { authoringDiagnostic, getAuthoringOperationDescriptor, validateAuthoringProject, type IAuthoringDiagnostic } from "@threenative/authoring";

import { classifyLiveSceneUpdate, type IEditorLiveSceneUpdate } from "../preview/liveSceneUpdates.js";
import { applyEditorOperationApi, type IEditorOperationApiResult } from "./operationApi.js";
import { editorChatContextFromProject, planEditorChatOperations, type IEditorChatPlan, type IEditorChatOperationStep } from "./chatPlan.js";
import { loadEditorProjectApi, validateProjectRoot } from "./projectApi.js";

export interface IEditorChatPlanApiRequest {
  message: string;
  selectedRowId?: string;
}

export interface IEditorChatApplyApiRequest {
  approvalToken?: string;
  plan?: IEditorChatPlan;
}

export interface IEditorChatApplyApiResult {
  changedSourceFiles: string[];
  diagnostics: IAuthoringDiagnostic[];
  generatedProofFiles: string[];
  liveUpdate: IEditorLiveSceneUpdate;
  ok: boolean;
  operationResults: IEditorOperationApiResult[];
  projectRevision?: string;
}

const CHAT_OPERATION_ALLOW_LIST = new Set([
  "scene.add_prefab",
  "scene.add_entity",
  "scene.set_transform",
  "scene.set_rigid_body",
  "scene.set_collider",
  "scene.set_visibility",
  "scene.add_tag",
]);

export async function planEditorChatApi(options: {
  projectPath: string;
  request: IEditorChatPlanApiRequest;
  rootPath?: string;
}): Promise<IEditorChatPlan> {
  const guard = validateProjectRoot(options.projectPath, options.rootPath);
  if (guard !== undefined) {
    return failedPlan(options.request.message, [guard]);
  }
  const project = await loadEditorProjectApi({ projectPath: options.projectPath, rootPath: options.rootPath });
  return planEditorChatOperations({
    context: editorChatContextFromProject(project, options.request.selectedRowId),
    message: options.request.message,
  });
}

export async function applyEditorChatApi(options: {
  projectPath: string;
  request: IEditorChatApplyApiRequest;
  rootPath?: string;
}): Promise<IEditorChatApplyApiResult> {
  const guard = validateProjectRoot(options.projectPath, options.rootPath);
  if (guard !== undefined) {
    return failedApply([guard]);
  }
  const plan = options.request.plan;
  if (plan === undefined || options.request.approvalToken === undefined || options.request.approvalToken !== plan.approvalToken || !plan.ok) {
    return failedApply([
      authoringDiagnostic({
        code: "TN_EDITOR_CHAT_APPROVAL_REQUIRED",
        message: "AI chat apply requires the approval token generated by a successful plan response.",
        path: "/approvalToken",
        suggestion: "Review the proposed operations and approve the current plan before applying it.",
      }),
    ]);
  }

  const guardDiagnostics = validateApplyPlan(plan);
  if (guardDiagnostics.length > 0) {
    return failedApply(guardDiagnostics);
  }

  const operationResults: IEditorOperationApiResult[] = [];
  const diagnostics: IAuthoringDiagnostic[] = [];
  let revision = plan.projectRevision;
  for (const [index, operation] of plan.operations.entries()) {
    const result = await applyEditorOperationApi({
      projectPath: options.projectPath,
      request: { args: operation.args, name: operation.name, projectRevision: revision },
      rootPath: options.rootPath,
    });
    operationResults.push(result);
    diagnostics.push(...result.diagnostics.map((diagnostic) => ({ ...diagnostic, path: diagnostic.path ?? `/operations/${index}` })));
    revision = result.projectRevision;
    if (!result.ok) {
      break;
    }
  }

  const sourceFiles = sourceFilesFromResults(operationResults);
  const validation = await validateAuthoringProject({ projectPath: options.projectPath });
  diagnostics.push(...validation.diagnostics);
  const ok = operationResults.length === plan.operations.length && operationResults.every((result) => result.ok) && validation.ok;
  return {
    changedSourceFiles: sourceFiles,
    diagnostics,
    generatedProofFiles: [],
    liveUpdate: classifyLiveSceneUpdate({ changedFiles: sourceFiles, operations: plan.operations }),
    ok,
    operationResults,
    projectRevision: revision,
  };
}

function validateApplyPlan(plan: IEditorChatPlan): IAuthoringDiagnostic[] {
  return plan.operations.flatMap((operation, index) => {
    const descriptor = getAuthoringOperationDescriptor(operation.name);
    if (descriptor === undefined || !CHAT_OPERATION_ALLOW_LIST.has(operation.name) || descriptor.pathPolicy !== "source-document") {
      return [
        authoringDiagnostic({
          code: "TN_EDITOR_CHAT_OPERATION_REJECTED",
          message: `AI chat operation '${operation.name}' is not approved for editor chat apply.`,
          path: `/operations/${index}/name`,
          suggestion: "Use a registered source-document operation from the editor chat plan endpoint.",
          value: operation.name,
        }),
      ];
    }
    const unsafePath = unsafePathValue(operation);
    if (unsafePath !== undefined) {
      return [
        authoringDiagnostic({
          code: "TN_EDITOR_CHAT_PATH_REJECTED",
          message: `AI chat operation '${operation.name}' references an unsafe path '${unsafePath}'.`,
          path: `/operations/${index}/args`,
          suggestion: "Chat operations may only target structured source paths inside the project.",
          value: unsafePath,
        }),
      ];
    }
    return [];
  });
}

function unsafePathValue(operation: IEditorChatOperationStep): string | undefined {
  for (const value of Object.values(operation.args)) {
    if (typeof value !== "string") {
      continue;
    }
    if (value.includes("..") || value.startsWith("/") || value.endsWith(".ir.json") || value === "assets.manifest.json" || value.includes("/dist/")) {
      return value;
    }
  }
  return undefined;
}

function sourceFilesFromResults(results: readonly IEditorOperationApiResult[]): string[] {
  return [...new Set(results.flatMap((result) => result.filesWritten).filter((file) => !isGeneratedProofFile(file)))].sort();
}

function isGeneratedProofFile(file: string): boolean {
  return file.endsWith(".ir.json") || file === "assets.manifest.json" || file.includes("/dist/");
}

function failedPlan(message: string, diagnostics: IAuthoringDiagnostic[]): IEditorChatPlan {
  return {
    affectedFiles: [],
    approvalToken: "",
    diagnostics,
    id: "",
    message,
    ok: false,
    operations: [],
    risks: [],
    summary: "AI chat could not produce a source-backed operation plan.",
  };
}

function failedApply(diagnostics: IAuthoringDiagnostic[]): IEditorChatApplyApiResult {
  return {
    changedSourceFiles: [],
    diagnostics,
    generatedProofFiles: [],
    liveUpdate: classifyLiveSceneUpdate({ changedFiles: [], operations: [] }),
    ok: false,
    operationResults: [],
  };
}
