import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  loadAuthoringProject,
  type IAuthoringDocument,
  type IInputDocument,
  type IMaterialDocument,
  type ISchemaDocument,
  type ISceneDocument,
} from "@threenative/authoring";
import type { IOverlaysIr, OverlayMessageSchemaKind } from "@threenative/ir";

export interface IGenerateProjectTypesOptions {
  outDir?: string;
  projectPath: string;
}

export interface IGenerateProjectTypesResult {
  files: string[];
  projectPath: string;
}

export async function generateProjectTypes(options: IGenerateProjectTypesOptions): Promise<IGenerateProjectTypesResult> {
  const projectPath = resolve(options.projectPath);
  const outDir = options.outDir ?? ".threenative/types";
  const project = await loadAuthoringProject({ projectPath });
  const output = generateProjectContextTypes(project.documents);
  const relativePath = `${outDir.replace(/\/+$/, "")}/project-context.d.ts`;
  await mkdir(resolve(projectPath, outDir), { recursive: true });
  await writeFile(resolve(projectPath, relativePath), output);
  return { files: [relativePath], projectPath };
}

export function generateProjectContextTypes(documents: readonly IAuthoringDocument[]): string {
  const ids = collectProjectIds(documents);
  const schemas = collectProjectSchemas(documents);
  const overlayMessages = collectOverlayMessages(documents);
  return [
    "import type { ScriptContext, ScriptEntity } from \"@threenative/script-stdlib\";",
    "",
    "// Generated by ThreeNative. Do not edit.",
    "",
    "export type ProjectEntityId = " + literalUnion(ids.entity) + ";",
    "export type ProjectEventId = " + literalUnion(ids.event) + ";",
    "export type ProjectInputId = " + literalUnion(ids.input) + ";",
    "export type ProjectMaterialId = " + literalUnion(ids.material) + ";",
    "export type ProjectPrefabId = " + literalUnion(ids.prefab) + ";",
    "export type ProjectResourceId = " + literalUnion(ids.resource) + ";",
    "export type ProjectSceneId = " + literalUnion(ids.scene) + ";",
    "export type ProjectUiId = " + literalUnion(ids.ui) + ";",
    "",
    "export interface ProjectComponentMap {",
    ...schemaRows(schemas.component),
    "}",
    "",
    "export interface ProjectResourceMap {",
    ...schemaRows(schemas.resource),
    "}",
    "",
    "export interface ProjectEventMap {",
    ...schemaRows(schemas.event),
    "}",
    "export type ProjectResourceValue<K extends ProjectResourceId> = K extends keyof ProjectResourceMap ? ProjectResourceMap[K] : unknown;",
    "export type ProjectResourcePatch<K extends ProjectResourceId> = ProjectResourceValue<K> extends Record<string, unknown> ? Partial<ProjectResourceValue<K>> : Record<string, unknown>;",
    "",
    "export interface ProjectGameToOverlayMessageMap {",
    ...schemaRows(overlayMessages.gameToOverlay),
    "}",
    "",
    "export interface ProjectOverlayToGameMessageMap {",
    ...schemaRows(overlayMessages.overlayToGame),
    "}",
    "",
    "export interface ProjectScriptEntity extends ScriptEntity {",
    "  get<K extends keyof ProjectComponentMap>(component: K): ProjectComponentMap[K];",
    "  get<K extends keyof ProjectComponentMap, T extends Record<string, unknown>>(component: K, defaults: T): ProjectComponentMap[K] & T;",
    "  patch<K extends keyof ProjectComponentMap>(component: K, value: Partial<ProjectComponentMap[K]>): void;",
    "  set<K extends keyof ProjectComponentMap>(component: K, value: ProjectComponentMap[K]): void;",
    "}",
    "",
    "export interface ProjectContext extends Omit<ScriptContext, \"entity\" | \"input\" | \"query\" | \"resources\"> {",
    "  entity(id: ProjectEntityId): ProjectScriptEntity | undefined;",
    "  input: Omit<ScriptContext[\"input\"], \"action\" | \"axis\" | \"getAxis\" | \"getAxis2\" | \"getButton\" | \"getButtonDown\" | \"getButtonUp\" | \"pressed\" | \"released\"> & {",
    "    action(name: ProjectInputId): boolean;",
    "    axis(name: ProjectInputId): number;",
    "    getAxis(axis: ProjectInputId): number;",
    "    getAxis2(xAxis: ProjectInputId, yAxis: ProjectInputId, options?: { deadzone?: number; normalize?: boolean }): [number, number];",
    "    getButton(name: ProjectInputId): boolean;",
    "    getButtonDown(name: ProjectInputId): boolean;",
    "    getButtonUp(name: ProjectInputId): boolean;",
    "    pressed(name: ProjectInputId): boolean;",
    "    released(name: ProjectInputId): boolean;",
    "  };",
    "  query(query?: Parameters<ScriptContext[\"query\"]>[0]): ProjectScriptEntity[];",
    "  resources: Omit<ScriptContext[\"resources\"], \"get\" | \"patch\" | \"set\"> & {",
    "    get<K extends ProjectResourceId>(name: K): ProjectResourceValue<K>;",
    "    get<K extends ProjectResourceId, T extends Record<string, unknown>>(name: K, defaults: T): ProjectResourceValue<K> & T;",
    "    patch<K extends ProjectResourceId>(name: K, value: ProjectResourcePatch<K>): void;",
    "    set<K extends ProjectResourceId>(name: K, value: ProjectResourceValue<K>): void;",
    "  };",
    "}",
    "",
  ].join("\n");
}

function collectOverlayMessages(documents: readonly IAuthoringDocument[]): Record<"gameToOverlay" | "overlayToGame", Map<string, Record<string, string>>> {
  const result = { gameToOverlay: new Map<string, Record<string, string>>(), overlayToGame: new Map<string, Record<string, string>>() };
  for (const document of documents) {
    if (document.kind !== "overlay") continue;
    const overlays = document.data as IOverlaysIr;
    for (const overlay of overlays.overlays ?? []) {
      for (const direction of ["gameToOverlay", "overlayToGame"] as const) {
        for (const message of overlay.messages[direction] ?? []) {
          result[direction].set(message.name, Object.fromEntries(Object.entries(message.schema.fields ?? {}).map(([name, kind]) => [name, overlayFieldType(kind)])));
        }
      }
    }
  }
  return result;
}

function overlayFieldType(kind: OverlayMessageSchemaKind): string {
  if (kind === "boolean") return "boolean";
  if (kind === "integer" || kind === "number") return "number";
  if (kind === "object") return "Record<string, unknown>";
  return "string";
}

interface ICollectedProjectIds {
  entity: string[];
  event: string[];
  input: string[];
  material: string[];
  prefab: string[];
  resource: string[];
  scene: string[];
  ui: string[];
}

function collectProjectIds(documents: readonly IAuthoringDocument[]): ICollectedProjectIds {
  const ids = {
    entity: new Set<string>(),
    event: new Set<string>(),
    input: new Set<string>(),
    material: new Set<string>(),
    prefab: new Set<string>(),
    resource: new Set<string>(),
    scene: new Set<string>(),
    ui: new Set<string>(),
  };
  for (const document of documents) {
    if (document.kind === "scene") {
      const scene = document.data as ISceneDocument;
      ids.scene.add(scene.id);
      for (const entity of scene.entities ?? []) ids.entity.add(entity.id);
      for (const instance of scene.instances ?? []) ids.entity.add(instance.id);
      for (const prefab of scene.prefabs ?? []) ids.prefab.add(prefab.id);
      for (const resource of scene.resources ?? []) ids.resource.add(resource.id);
      for (const node of scene.ui?.nodes ?? []) ids.ui.add(node.id);
    } else if (document.kind === "input") {
      const input = document.data as IInputDocument;
      for (const action of input.actions ?? []) ids.input.add(action.id);
      for (const axis of input.axes ?? []) ids.input.add(axis.id);
    } else if (document.kind === "material") {
      const material = document.data as IMaterialDocument;
      for (const entry of material.materials ?? []) ids.material.add(entry.id);
    } else if (document.kind === "schema") {
      const schemaDocument = document.data as ISchemaDocument;
      if (schemaDocument.kind === "event") {
        for (const entry of schemaDocument.schemas ?? []) ids.event.add(entry.id);
      }
    }
  }
  return {
    entity: [...ids.entity].sort(),
    event: [...ids.event].sort(),
    input: [...ids.input].sort(),
    material: [...ids.material].sort(),
    prefab: [...ids.prefab].sort(),
    resource: [...ids.resource].sort(),
    scene: [...ids.scene].sort(),
    ui: [...ids.ui].sort(),
  };
}

function collectProjectSchemas(documents: readonly IAuthoringDocument[]): Record<"component" | "event" | "resource", Map<string, Record<string, string>>> {
  const schemas = { component: new Map<string, Record<string, string>>(), event: new Map<string, Record<string, string>>(), resource: new Map<string, Record<string, string>>() };
  for (const document of documents) {
    if (document.kind !== "schema") continue;
    const schemaDocument = document.data as ISchemaDocument;
    if (!Array.isArray(schemaDocument.schemas)) continue;
    for (const entry of schemaDocument.schemas) {
      schemas[schemaDocument.kind].set(entry.id, Object.fromEntries(Object.entries(entry.fields).map(([name, field]) => [name, fieldType(field.kind)])));
    }
  }
  for (const document of documents) {
    if (document.kind !== "scene") continue;
    const scene = document.data as ISceneDocument;
    for (const entity of scene.entities ?? []) {
      for (const component of Object.keys(entity.components ?? {})) {
        if (!schemas.component.has(component)) {
          schemas.component.set(component, { "[key: string]": "unknown" });
        }
      }
    }
  }
  return schemas;
}

function schemaRows(schemas: Map<string, Record<string, string>>): string[] {
  return [...schemas.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([id, fields]) => `  ${JSON.stringify(id)}: { ${Object.entries(fields).map(([name, type]) => `${name === "[key: string]" ? name : JSON.stringify(name)}${type.includes("undefined") ? "?" : ""}: ${type.replace(" | undefined", "")}`).join("; ")} };`);
}

function fieldType(kind: string): string {
  switch (kind) {
    case "boolean":
      return "boolean";
    case "color":
    case "enum":
    case "string":
      return "string";
    case "number":
      return "number";
    case "quat":
      return "[number, number, number, number]";
    case "vec2":
      return "[number, number]";
    case "vec3":
      return "[number, number, number]";
    case "vec4":
      return "[number, number, number, number]";
    default:
      return "unknown";
  }
}

function literalUnion(values: readonly string[]): string {
  return values.length === 0 ? "string" : values.map((value) => JSON.stringify(value)).join(" | ");
}
