export {
  AngleEx,
  ArrayEx,
  Bounds2,
  Bounds3,
  BasisEx,
  CameraMath,
  CheckpointRaceEx,
  ColorEx,
  ControllerEx,
  Ease,
  InputEx,
  MotionEx,
  Mathf,
  MaterialEx,
  NumberEx,
  Quat,
  RandomEx,
  SpawnEx,
  TextEx,
  TimerEx,
  TransformMath,
  Vector2,
  Vector3,
  Vec2,
  Vec3,
} from "./helpers.js";
export type { IMaterialPatch } from "./feedback.js";
export { CameraRig, CharacterRig, KinematicMoverEx, RespawnEx, TriggerEx } from "./rigs.js";
export { defineBehavior } from "./behavior.js";
export { vehicle, type VehicleFacade } from "./physics.js";
export type { BehaviorFunction, BehaviorSchedule, IBehaviorCommandMetadata, IBehaviorFunction, IBehaviorMetadata, IBehaviorQueryMetadata } from "./behavior.js";
export type {
  ICameraRigOptions,
  ICameraRigResult,
  ICharacterRigClipOptions,
  ICharacterRigOptions,
  ICharacterRigResult,
  IKinematicMoverExOptions,
  IKinematicMoverExResult,
  IOrbitCameraRigOptions,
  IOrbitCameraRigResult,
  IRespawnExOptions,
  IRespawnExResult,
  ITriggerExOptions,
} from "./rigs.js";

export { SCRIPT_STDLIB_BUNDLE_SOURCE } from "./bundle-source.js";
export type { ColorTuple, ColorValue, QuatTuple, QuatValue, Vec2Tuple, Vec2Value, Vec3Tuple, Vec3Value } from "./helpers.js";
export type {
  ScriptAnimationFacade,
  ScriptAssetsFacade,
  ScriptAudioFacade,
  ScriptCamerasFacade,
  ScriptChannelsFacade,
  ScriptCharacterFacade,
  ScriptCommandsFacade,
  ScriptComponentsFacade,
  ScriptContext,
  ScriptCoreContextFacades,
  ScriptDataContextFacades,
  ScriptEffectsFacade,
  ScriptEntitiesFacade,
  ScriptEntity,
  ScriptEntityLifecycleQueryOptions,
  ScriptEventsFacade,
  ScriptInputFacade,
  ScriptNavigationFacade,
  ScriptObserversFacade,
  ScriptParticlesFacade,
  ScriptPersistenceFacade,
  ScriptPhysicsFacade,
  ScriptPhysicsVehicleFacade,
  ScriptPickingFacade,
  ScriptPluginsFacade,
  ScriptPresentationContextFacades,
  ScriptQuatTuple,
  ScriptRandomFacade,
  ScriptResourcesFacade,
  ScriptScenesFacade,
  ScriptScheduleFacade,
  ScriptSequencesFacade,
  ScriptSettingsFacade,
  ScriptStatesFacade,
  ScriptTasksFacade,
  ScriptTimeFacade,
  ScriptTimersFacade,
  ScriptTransformFacade,
  ScriptUiFacade,
  ScriptVec3Tuple,
  ScriptWorldContextFacades,
} from "./script-context.js";
